# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zcqNEbJnjpWBAcN_K_z3Wu-FEH8CkRUX
"""

import streamlit as st
import numpy as np
import joblib

# load trained model
model = joblib.load("placement_model.pkl")

# title
st.title("🎓 Student Placement Risk & Readiness Analysis System")

st.write("Enter student details below:")

# user inputs
overall = st.slider("Overall Academic Score", 0, 100)
etest = st.slider("Aptitude Test Score", 0, 100)
workex = st.selectbox("Work Experience", ["No", "Yes"])

# convert workex
workex_val = 1 if workex == "Yes" else 0

# readiness score
readiness_score = (0.4 * overall) + (0.3 * etest) + (0.3 * workex_val * 100)

# readiness level
if readiness_score >= 75:
    readiness = "High"
elif readiness_score >= 60:
    readiness = "Medium"
else:
    readiness = "Low"

# risk level
if readiness_score < 60:
    risk = "High Risk"
elif readiness_score < 75:
    risk = "Medium Risk"
else:
    risk = "Low Risk"

# prediction using model
input_data = np.array([[overall, etest, workex_val]])
pred = model.predict(input_data)[0]

# analysis function
def student_analysis(pred, readiness, risk):

    if pred == 1:
        placement = "High Probability of Placement"
    else:
        placement = "Low Probability of Placement"

    if readiness == "High":
        readiness_msg = "You are well-prepared and ready to grab opportunities."
        motivation = "Keep pushing forward — success is within your reach!"
    elif readiness == "Medium":
        readiness_msg = "You are on the right track but there is room for improvement."
        motivation = "Stay consistent and keep improving — you’re closer than you think!"
    else:
        readiness_msg = "You need to work on your skills and preparation."
        motivation = "Don’t give up — every expert was once a beginner. Start improving today!"

    if risk == "Low Risk":
        risk_msg = "Low risk — your profile is strong."
    elif risk == "Medium Risk":
        risk_msg = "Moderate risk — focus on improving key areas."
    else:
        risk_msg = "High risk — immediate improvement is required to boost your chances."

    return f"""
🔹 Placement Prediction: {placement}
🔹 Readiness Level: {readiness}
🔹 Risk Level: {risk}

📊 Analysis:
{readiness_msg}
{risk_msg}

💡 Motivation:
{motivation}
"""

# button
if st.button("Analyze Student"):
    result = student_analysis(pred, readiness, risk)
    st.text(result)