# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mb11mp4Z8qHRvfWF2sovhQjGkBNizQXp
"""

import streamlit as st
import pickle
import numpy as np

# ===== LOAD MODEL =====
model = pickle.load(open('model.pkl', 'rb'))
scaler = pickle.load(open('scaler.pkl', 'rb'))

st.title("Student Placement Risk & Readiness Analysis System")

# ===== INPUT FIELDS =====

cgpa = st.number_input("CGPA")
tenth = st.number_input("10th Percentage")
twelfth = st.number_input("12th Percentage")
backlogs = st.number_input("Backlogs")

study_hours = st.number_input("Study Hours per Day")
attendance = st.number_input("Attendance Percentage")

projects = st.number_input("Projects Completed")
internships = st.number_input("Internships Completed")

coding = st.number_input("Coding Skill Rating (1-5)")
communication = st.number_input("Communication Skill Rating (1-5)")
aptitude = st.number_input("Aptitude Skill Rating (1-5)")

hackathons = st.number_input("Hackathons Participated")
certifications = st.number_input("Certifications Count")

stress = st.number_input("Stress Level (1-10)")

# ===== CATEGORICAL INPUTS =====

gender = st.selectbox("Gender", ["Male", "Female"])
branch = st.selectbox("Branch", ["CSE", "IT", "ECE", "Mechanical", "Civil"])
part_time = st.selectbox("Part Time Job", ["Yes", "No"])
income = st.selectbox("Family Income", ["Low", "Medium", "High"])
city = st.selectbox("City Tier", ["Tier 1", "Tier 2", "Tier 3"])
extra = st.selectbox("Extracurricular Involvement", ["Yes", "No"])

# ===== ENCODING =====

gender = 1 if gender == "Male" else 0
part_time = 1 if part_time == "Yes" else 0
extra = 1 if extra == "Yes" else 0

income_map = {"Low": 0, "Medium": 1, "High": 2}
income = income_map[income]

city_map = {"Tier 1": 2, "Tier 2": 1, "Tier 3": 0}
city = city_map[city]

branch_map = {"CSE": 0, "IT": 1, "ECE": 2, "Mechanical": 3, "Civil": 4}
branch = branch_map[branch]

# ===== ANALYSIS FUNCTION =====

def student_analysis(pred, readiness, risk):
    if pred == 1:
        placement = "Placed (High Probability)"
    else:
        placement = "Not Placed (Low Probability)"

    if readiness == "High":
        readiness_msg = "You are well prepared for placements."
        motivation = "Great job! Keep improving and stay consistent."
    elif readiness == "Medium":
        readiness_msg = "You are moderately prepared but need improvement."
        motivation = "Focus on skills and practice more — you can do it!"
    else:
        readiness_msg = "You are not ready yet for placements."
        motivation = "Start working on your skills — improvement is possible!"

    if risk == "Low Risk":
        risk_msg = "Your risk is low. You have good chances of placement."
    else:
        risk_msg = "Your risk is high. You need to improve your profile."

    return f"""
Placement Prediction: {placement}

Readiness Level: {readiness}
Risk Level: {risk}

Analysis:
{readiness_msg}
{risk_msg}

Motivation:
{motivation}
"""

# ===== PREDICTION =====

if st.button("Predict"):

    data = np.array([[
        gender, branch, cgpa, tenth, twelfth, backlogs,
        study_hours, attendance, projects, internships,
        coding, communication, aptitude,
        hackathons, certifications,
        stress, part_time, income, city,
        extra
    ]])

    data = scaler.transform(data)
    prediction = model.predict(data)

    # ===== RESULT =====
    if prediction[0] == 1:
        result = "Placed"
        risk = "Low Risk"
    else:
        result = "Not Placed"
        risk = "High Risk"

    # ===== READINESS =====
    score = cgpa + internships + coding

    if score >= 12:
        readiness = "High"
    elif score >= 8:
        readiness = "Medium"
    else:
        readiness = "Low"

    # ===== DISPLAY =====
    st.success(f"Prediction: {result}")
    st.info(f"Risk Level: {risk}")
    st.warning(f"Readiness Level: {readiness}")

    # ===== ANALYSIS OUTPUT =====
    analysis = student_analysis(prediction[0], readiness, risk)
    st.text(analysis)